### ISSUE TITLE
ошибка при загрузке фото в NGW

### ISSUE THREAD

**Issue by ABiatov** [nextgis/IdentifyPlus#17]
1. Создал точечный слой, загрузил его в NGW через NG Connect
2. Через веб-интерфейс создал WFS-сервис и подключил в него несколько слоев, в том числе и  вышеупомянутый точечный слой.
3. Используя NG Connect подключил этот  слой в NG QGIS через WFS
4. Включил редактирование, добавил точку и сохранил изменения.
5. Кликнул по точке инструментом IdentyfyPlus.
6. Перешел на вкладку "Фото (ngw)"
7. нажал ➕чтоб добавить фото.
8. в браузере файлов выбрал нужную фотографию
9. нажал кнопку "Открыть" и получил выше приведенную ошибку.

```
2021-02-22T23:23:51   1   Traceback (most recent call last):
File "C:/Users/biato\.config\\NextGIS\qgis2\python/plugins\identifyplus\identifytool_ngw.py", line 413, in addImage
  self.__model.addImage(file_name)
File "C:/Users/biato\.config\\NextGIS\qgis2\python/plugins\identifyplus\identifytool_ngw.py", line 131, in addImage
uploaded_file_info = self.__ngw_feature.ngw_resource._res_factory.connection.upload_file(image_filename)
AttributeError: 'NGWFeature' object has no attribute 'ngw_resource'

```
Если я добавляю этот же слой непосредственно через NGConnect (как geojson а не wfs) и пытаюсь в эту же точку добавить фото таким же способом через IdentifyPlus,  выдает туже ошибку.

Через веб-карту фото в аттачмент к этой (созданной через WFS) точке загрузилась без проблем.

При этом IdentifyPlus видит фотки в аттачменте в слое который подключен по WFS.  И даже позволяет скачать их на комп. Фотки были добавлены через NGM и через веб-карту

**Comment by simgislab** [comment]
закрываю, переусложненный кейс, сначала надо решить #18 
потом можно потестить это вместе с WFS и подумать как ограничиться только WFS (без параллельного геоджейсона для фоток)
